set_property IOSTANDARD LVCMOS33 [get_ports {sortieA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sortieB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RST]

set_property PACKAGE_PIN L1 [get_ports {sortieA[7]}]
set_property PACKAGE_PIN P1 [get_ports {sortieA[6]}]
set_property PACKAGE_PIN N3 [get_ports {sortieA[5]}]
set_property PACKAGE_PIN P3 [get_ports {sortieA[4]}]
set_property PACKAGE_PIN U3 [get_ports {sortieA[3]}]
set_property PACKAGE_PIN W3 [get_ports {sortieA[2]}]
set_property PACKAGE_PIN V3 [get_ports {sortieA[1]}]
set_property PACKAGE_PIN V13 [get_ports {sortieA[0]}]
set_property PACKAGE_PIN V14 [get_ports {sortieB[7]}]
set_property PACKAGE_PIN U14 [get_ports {sortieB[6]}]
set_property PACKAGE_PIN U15 [get_ports {sortieB[5]}]
set_property PACKAGE_PIN W18 [get_ports {sortieB[4]}]
set_property PACKAGE_PIN V19 [get_ports {sortieB[3]}]
set_property PACKAGE_PIN U19 [get_ports {sortieB[2]}]
set_property PACKAGE_PIN E19 [get_ports {sortieB[1]}]
set_property PACKAGE_PIN U16 [get_ports {sortieB[0]}]

set_property PACKAGE_PIN U18 [get_ports CLK]
set_property PACKAGE_PIN U17 [get_ports RST]


set_property IOSTANDARD LVCMOS33 [get_ports {pc_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc_out[0]}]
